# Generated by Django 2.1.5 on 2019-02-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_auto_20190202_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam'), ('Hindi', 'Hindi')], default='English', max_length=10),
        ),
    ]
