# Generated by Django 2.1.5 on 2019-02-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='book',
        ),
        migrations.RemoveField(
            model_name='log',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
