# Generated by Django 2.1.5 on 2019-02-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam'), ('Hindi', 'Hindi')], default='English', max_length=10),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
