# Generated by Django 2.1.5 on 2019-02-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_auto_20190206_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EI', 'Electronics and Instrumentation'), ('EC', 'Electronics and Communication'), ('CE', 'Civil'), ('EEE', 'Electrical & Electronics')], default='CS', max_length=2)),
                ('Semester', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8')], default='S5', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.Log_user'),
        ),
    ]
