# Generated by Django 2.1.5 on 2019-02-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0008_auto_20190206_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(blank=True, choices=[('On loan', 'On loan'), ('Available', 'Available'), ('Reserved', 'Reserved')], default='Available', help_text='Book availability', max_length=3),
        ),
    ]
