# Generated by Django 2.1.5 on 2019-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0009_auto_20190206_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(blank=True, choices=[('On loan', 'On loan'), ('Available', 'Available'), ('Reserved', 'Reserved')], help_text='Book availability', max_length=3),
        ),
    ]
