# Generated by Django 2.1.5 on 2019-02-06 17:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('bookshelf', '0013_auto_20190206_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_Logger',
            new_name='A_Log',
        ),
        migrations.RenameModel(
            old_name='Log_user',
            new_name='User_Log',
        ),
    ]
