# Generated by Django 2.1.5 on 2019-02-06 17:03

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('bookshelf', '0014_auto_20190206_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Log',
            new_name='Log_user',
        ),
    ]
