# Generated by Django 2.1.5 on 2019-02-06 17:06

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('bookshelf', '0015_auto_20190206_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A_Log',
            new_name='Log',
        ),
    ]
