# Generated by Django 2.1.5 on 2019-02-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0017_auto_20190206_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='a_logger',
            name='bar_code_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.BarCode'),
        ),
    ]
