# Generated by Django 2.1.5 on 2019-02-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0018_auto_20190207_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='number_code',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
    ]
