# Generated by Django 2.1.5 on 2019-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0019_auto_20190207_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='number_code',
            field=models.IntegerField(),
        ),
    ]
