# Generated by Django 2.1.5 on 2019-02-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0021_book_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='number_code',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='Code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.BarCode'),
        ),
    ]
