# Generated by Django 2.1.5 on 2019-02-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0023_remove_barcode_number_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='number_code',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
