# Generated by Django 2.1.5 on 2019-02-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0024_barcode_number_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_user',
            name='Branch',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech')], default='B.Tech', max_length=7),
        ),
        migrations.AlterField(
            model_name='log_user',
            name='Department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], default='CS', max_length=2),
        ),
    ]
